apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webserv1
  name: webserv1
spec:
  containers:
  - image: nginx
    name: webserv1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
