apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus-1
    service: webserver
  name: girus
spec:
  containers:
  - image: nginx 
    name: girus
    resources: {}
  - image: busybox 
    name: busybox
    args: 
    - sleep 
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
